#!/bin/bash
# $Id$
#-------------------------------------------------------------------------------
# Description:
# Script to run WRF's Hurricane Katrina case.

# Initialize options.
PLOT_OUTPUT=0

while true;
do
   case "$1" in
      --plot-output) # Option to plot the output.
             PLOT_OUTPUT=1
             shift;;
      -h|--help) # Print help messge.
             echo -e "Usage: run_Katrina.bash [OPTIONS]"
             exit 1;;
      --) shift; break;;
      *) break;;
   esac
done

# Figure out the directory where the script is located.
run_dir=`dirname $0`

# Change the directory to the one in which the script is located.
cd $run_dir

#---------------------------------------------------------------------------
# Compile WRF first.  It must be compiled before WPS can be compiled.

# Change the directory to WRF.
cd ../../

# Copy the custom configuration file for WRF-CLUBB.
cp custom_config_files/configure.wrf.intel64.serial.clubb configure.wrf

# Compile WRF.
./compile em_real

#---------------------------------------------------------------------------
# WPS

# Change the directory to WPS.
cd ../WPS

# Copy the custom configuration file to configure.wps.
cp custom_config_files/configure.wps.intel64.serial.grib2.WRF-CLUBB configure.wps

# Compile WPS.
./compile

# Compile additional utilities plotgrids.exe and plotfmt.exe.
./compile util

# Move the current namelist (namelist.wps) to namelist.wps.default.
mv namelist.wps namelist.wps.default

# Copy namelist.wps.Katrina to namelist.wps.
cp namelist.wps.Katrina namelist.wps

#-----------------------------
# WPS geogrid

# Remove any geo_em.*.nc files already found.
rm geo_em.*.nc

# Run geogrid.exe, which produces the file geo_em.d01.nc.
./geogrid.exe

#-----------------------------
# WPS ungrib

# Change the directory to the DATA directory.
cd ../DATA

# Retrieve the input data and place it in the DATA directory.
# Check that the data is available.
wget --spider http://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/Katrina.tar.gz

# If status = 0, the file is available.  Otherwise, status != 0.
STATUS=$?

if [ $STATUS == 0 ]; then
   # Download the data file for the Hurricane Katrina input data, which is used
   # by WPS for the initial conditions and boundary conditions.
   wget http://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/Katrina.tar.gz
else # $STATUS != 0
   # The file wasn't found.
   echo "The link to the Hurricane Katrina input data is broken."
   exit 1
fi # $STATUS == 0

# Extract the files into the DATA/Katrina directory.
tar -xzvf Katrina.tar.gz

# Remove the Katrina.tar.gz file.
rm -f Katrina.tar.gz

# Change the directory back to the WPS directory.
cd ../WPS

# Link the appropriate Vtable for the input data.
ln -sf ungrib/Variable_Tables/Vtable.GFS Vtable

# Link the GRIB data.
./link_grib.csh ../DATA/Katrina/avn

# Remove any FILE: files already found.
rm FILE\:*

# Run ungrib.exe, which produces files that are used to help provide information
# on initial conditions and lateral boundary conditions to WRF.
./ungrib.exe

# Change the directory to the DATA directory.
cd ../DATA

# Retrieve the input data on SST and place it in the DATA directory.
# Check that the data is available.
wget --spider http://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/SST.tar.gz

# If status = 0, the file is available.  Otherwise, status != 0.
STATUS=$?

if [ $STATUS == 0 ]; then
   # Download the data file for the Hurricane Katrina SST input data.
   wget http://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/SST.tar.gz
else # $STATUS != 0
   # The file wasn't found.
   echo "The link to the Hurricane Katrina SST input data is broken."
   exit 1
fi # $STATUS == 0

# Extract the files into the DATA/SST directory.
tar -xzvf SST.tar.gz

# Remove the Katrina.tar.gz file.
rm -f SST.tar.gz

# Change the directory back to the WPS directory.
cd ../WPS

# Link the appropriate Vtable for the SST input data.
ln -sf ungrib/Variable_Tables/Vtable.SST Vtable

# Link the GRIB data for SST.
./link_grib.csh ../DATA/SST/rtg_sst_grb_0.5

# Edit namelist.wps.
sed -i "s/prefix = 'FILE'/prefix = 'SST'/g" namelist.wps

# Remove any SST: files already found.
rm SST\:*

# Run ungrib.exe, which produces files that are used to help provide information
# on sea surface temperature.
./ungrib.exe

#-----------------------------
# WPS metgrid

# Remove any met_em.* files already found.
rm met_em.*

# Run metgrid.exe, which interpolates the input data onto the module domain.
./metgrid.exe

#-----------------------------

# Move namelist.wps.default back to namelist.wps.
mv namelist.wps.default namelist.wps

#---------------------------------------------------------------------------
# WRF

# Change the directory to the one in which this script is located.
cd ../WRF/test/em_real

# Link the met_em.* files generated by metgrid.exe.
ln -sf ../../../WPS/met_em.d01.2005-08* .

# Move the current namelist (namelist.input) to namelist.input.default.
mv namelist.input namelist.input.default

# Copy namelist.input.Katrina namelist.input.
cp namelist.input.Katrina namelist.input

# Remove any wrfinput_d01 and wrfbdy_d01 files that are found.
rm wrfinput_d01
rm wrfbdy_d01

# Run real.exe to generate wrfinput_d01 and wrfbdy_d01 files.
./real.exe

# Run WRF.
./wrf.exe | tee wrf_run_output.txt

# Move namelist.input.default back to namelist.input.
mv namelist.input.default namelist.input

#---------------------------------------------------------------------------
# ARWpost

# Change the directory to ARWpost.
cd ../../../ARWpost

# Copy the custom configuration file to configure.arwp.
cp custom_config_files/configure.arwp.intel64.WRF-CLUBB configure.arwp

# Compile ARWpost.
./compile

# Move the current namelist (namelist.arwp) to namelist.arwp.default.
mv namelist.ARWpost namelist.ARWpost.default

# Copy namelist.arwp.Katrina to namelist.arwp.
cp namelist.ARWpost.Katrina namelist.ARWpost

# Run ARWpost.
./ARWpost.exe

# Move namelist.arwp.default back to namelist.arwp.
mv namelist.ARWpost.default namelist.ARWpost

# Plot the output.
if [ $PLOT_OUTPUT -eq 1 ]; then

   # Change directory to the output_plots directory.
   cd output_plots

   # Run the WRF(-CLUBB) plotting script.
   ./plot_wrf_output.bash --clubb-zt ../../WRF/test/em_real/clubb_zt.ctl --clubb-zm ../../WRF/test/em_real/clubb_zm.ctl --clubb-sfc ../../WRF/test/em_real/clubb_sfc.ctl ../Katrina.ctl

   # Zip the plots into the plot_Katrina.maff file.
   zip -r plot_Katrina.maff output/

   # E-mail the plots to interested users.
   echo "The WRF(-CLUBB) Hurricane Katrina plots are ready.  Please view the attachment." | mail -s "WRF(-CLUBB) Katrina plots" -a plot_Katrina.maff bmg2@uwm.edu,vlarson@uwm.edu

fi # $PLOT_OUTPUT -eq 1
